Goal: Clean and transform messy concert tours dataset into analysis-ready format.

In [96]:
from google.colab import files
uploaded = files.upload()

Saving my_file (1).csv to my_file (1) (3).csv

In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [98]:
df = pd.read_csv('/content/my_file (1).csv')
df.head(20)

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

In [100]:
df.isnull().sum()

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [101]:
df.shape

(20, 11)

In [102]:
df = df.drop('Peak',axis=1)
df = df.drop('All Time Peak',axis=1)
df

,Rank,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [103]:
df.value_counts()

Rank  Actual gross     Adjusted gross (in 2022 dollars)  Artist        Tour title                                Year(s)    Shows  Average gross  Ref.
1     $780,000,000     $780,000,000                      Taylor Swift  The Eras Tour †                           2023–2024  56     $13,928,571    [1]         1
2     $579,800,000     $579,800,000                      Beyoncé       Renaissance World Tour                    2023       56     $10,353,571    [3]         1
3     $411,000,000     $560,622,615                      Madonna       Sticky & Sweet Tour ‡[4][a]               2008–2009  85     $4,835,294     [6]         1
4     $397,300,000     $454,751,555                      Pink          Beautiful Trauma World Tour               2018–2019  156    $2,546,795     [7]         1
5     $345,675,146     $402,844,849                      Taylor Swift  Reputation Stadium Tour                   2018       53     $6,522,173     [8]         1
6     $305,158,363     $388,978,496                      Madonna       The MDNA Tour                             2012       88     $3,467,709     [9]         1
7     $257,600,000     $257,600,000                      Pink          Summer Carnival †                         2023–2024  41     $6,282,927     [12]        1
      $280,000,000     $381,932,682                      Celine Dion   Taking Chances World Tour                 2008–2009  131    $2,137,405     [11]        1
9     $256,084,556     $312,258,401                      Beyoncé       The Formation World Tour                  2016       49     $5,226,215     [13]        1
10    $250,400,000     $309,141,878                      Taylor Swift  The 1989 World Tour                       2015       85     $2,945,882     [14]        1
11    $229,100,000[b]  $283,202,896                      Beyoncé       The Mrs. Carter Show World Tour           2013–2014  132    $1,735,606     [15][16]    1
12    $227,400,000     $295,301,479                      Lady Gaga     The Monster Ball Tour *                   2009–2011  203    $1,118,227     [18]        1
13    $204,000,000     $251,856,802                      Katy Perry    Prismatic World Tour                      2014–2015  151    $1,350,993     [19]        1
14    $200,000,000     $299,676,265                      Cher          Living Proof: The Farewell Tour ‡[21][a]  2002–2005  325    $615,385       [20]        1
15    $194,000,000     $281,617,035                      Madonna       Confessions Tour                          2006       60     $3,233,333     [5]         1
16    $184,000,000     $227,452,347                      Pink          The Truth About Love Tour                 2013–2014  142    $1,295,775     [22]        1
17    $170,000,000     $213,568,571                      Lady Gaga     Born This Way Ball                        2012–2013  98     $1,734,694     [d]         1
18    $169,800,000     $207,046,755                      Madonna       Rebel Heart Tour                          2015–2016  82     $2,070,732     [4]         1
19    $167,700,000[e]  $204,486,106                      Adele         Adele Live 2016                           2016–2017  121    $1,385,950     [25]        1
20    $150,000,000     $185,423,109                      Taylor Swift  The Red Tour                              2013–2014  86     $1,744,186     [26]        1
Name: count, dtype: int64

In [124]:
# Faraz: Adjusted gross 3-ustun, Average gross 4-ustun (nomlarini bilmagan holda)
# Lekin nomini bilish yaxshiroq. Eng ishonchli:
df.iloc[:, [1,2,7]] = df.iloc[:,[1,2,7]].apply(lambda x: x.replace(r'[\$,eb\[\]\(\)]', '', regex=True).astype(float))

/tmp/ipykernel_1155/4198874609.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.iloc[:, [1,2,7]] = df.iloc[:,[1,2,7]].apply(lambda x: x.replace(r'[\$,eb\[\]\(\)]', '', regex=True).astype(float))
/tmp/ipykernel_1155/4198874609.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.iloc[:, [1,2,7]] = df.iloc[:,[1,2,7]].apply(lambda x: x.replace(r'[\$,eb\[\]\(\)]', '', regex=True).astype(float))
/tmp/ipykernel_1155/4198874609.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.iloc[:, [1,2,7]] = df.iloc[:,[1,2,7]].apply(lambda x: x.replace(r'[\$,eb\[\]\(\)]', '', regex=True).astype(float))

In [129]:
df.columns = df.columns.str.replace(r'[^a-zA-Z0-9\s&]', '', regex=True)

In [131]:
print(df.columns)

Index(['Rank', 'Actual  gross', 'Adjusted  gross in 2022 dollars', 'Artist',
       'Tour title', 'Years', 'Shows', 'Average gross', 'Ref'],
      dtype='object')

In [134]:
df.columns = (
    df.columns
    .str.replace(r'\s+', ' ', regex=True)  # 2+ space → 1 ta space
    .str.strip()
)

In [135]:
print(df.columns.tolist())

['Rank', 'Actual gross', 'Adjusted gross in 2022 dollars', 'Artist', 'Tour title', 'Years', 'Shows', 'Average gross', 'Ref']

In [136]:
df[['Actual gross','Adjusted gross in 2022 dollars','Average gross']] = \
df[['Actual gross','Adjusted gross in 2022 dollars','Average gross']].astype(int)

In [137]:
df['Tour title']

0                              The Eras Tour †
1                       Renaissance World Tour
2                  Sticky & Sweet Tour ‡[4][a]
3                  Beautiful Trauma World Tour
4                      Reputation Stadium Tour
5                                The MDNA Tour
6                    Taking Chances World Tour
7                            Summer Carnival †
8                     The Formation World Tour
9                          The 1989 World Tour
10             The Mrs. Carter Show World Tour
11                     The Monster Ball Tour *
12                        Prismatic World Tour
13    Living Proof: The Farewell Tour ‡[21][a]
14                            Confessions Tour
15                   The Truth About Love Tour
16                          Born This Way Ball
17                            Rebel Heart Tour
18                             Adele Live 2016
19                                The Red Tour
Name: Tour title, dtype: object

In [138]:
df['Tour title'] = (
    df['Tour title']
    .str.replace(r'\[.*?\]', '', regex=True)
    .str.replace(r'[^a-zA-Z0-9\s&]', '', regex=True)
    .str.strip()
)

In [141]:
df = df.drop('Ref',axis=1)
df

,Rank,Actual gross,Adjusted gross in 2022 dollars,Artist,Tour title,Years,Shows,Average gross
0,1,780000000,780000000,Taylor Swift,The Eras Tour,2023–2024,56,13928571
1,2,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571
2,3,411000000,560622615,Madonna,Sticky & Sweet Tour,2008–2009,85,4835294
3,4,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795
4,5,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173
5,6,305158363,388978496,Madonna,The MDNA Tour,2012,88,3467709
6,7,280000000,381932682,Celine Dion,Taking Chances World Tour,2008–2009,131,2137405
7,7,257600000,257600000,Pink,Summer Carnival,2023–2024,41,6282927
8,9,256084556,312258401,Beyoncé,The Formation World Tour,2016,49,5226215
9,10,250400000,309141878,Taylor Swift,The 1989 World Tour,2015,85,2945882
10,11,229100000,283202896,Beyoncé,The Mrs Carter Show World Tour,2013–2014,132,1735606
11,12,227400000,295301479,Lady Gaga,The Monster Ball Tour,2009–2011,203,1118227
12,13,204000000,251856802,Katy Perry,Prismatic World Tour,2014–2015,151,1350993
13,14,200000000,299676265,Cher,Living Proof The Farewell Tour,2002–2005,325,615385
14,15,194000000,281617035,Madonna,Confessions Tour,2006,60,3233333
15,16,184000000,227452347,Pink,The Truth About Love Tour,2013–2014,142,1295775
16,17,170000000,213568571,Lady Gaga,Born This Way Ball,2012–2013,98,1734694
17,18,169800000,207046755,Madonna,Rebel Heart Tour,2015–2016,82,2070732
18,19,167700000,204486106,Adele,Adele Live 2016,2016–2017,121,1385950
19,20,150000000,185423109,Taylor Swift,The Red Tour,2013–2014,86,1744186

In [143]:
df['Years']

0     2023–2024
1          2023
2     2008–2009
3     2018–2019
4          2018
5          2012
6     2008–2009
7     2023–2024
8          2016
9          2015
10    2013–2014
11    2009–2011
12    2014–2015
13    2002–2005
14         2006
15    2013–2014
16    2012–2013
17    2015–2016
18    2016–2017
19    2013–2014
Name: Years, dtype: object

In [149]:
# year(s) utsuni ustida tozalash va togirlash ishlarini ol;ib borish
# 1 qadam: belginio normalizatsiya qilish

df['Years'] = df['Years'].str.replace(r'[–—−]', '-', regex=True)

# 2-qadam split qilish

years =df['Years'].str.split('-',expand=True)

# 3-qadam yangi ustunlar yaratish

df['start_year']= years[0]
df['end_year'] = years[1]

# 4- qadam bosh end_yearni toldirish

df['end_year'] = df['end_year'].fillna(df['start_year'])

# 5-qadam INT ga otkazish

df['start_year'] = df['start_year'].astype(int)
df['end_year']= df['end_year'].astype(int)

In [155]:
df = df.drop('Years', axis=1)

In [163]:
df.to_csv("cleaned_data.csv", index=False)